# 
# Synthesis run script generated by Vivado
# 

namespace eval rt {
    variable rc
}
set rt::rc [catch {
  uplevel #0 {
    set ::env(BUILTIN_SYNTH) true
    source $::env(HRT_TCL_PATH)/rtSynthPrep.tcl
    rt::HARTNDb_startJobStats
    set rt::cmdEcho 0
    rt::set_parameter writeXmsg true
    rt::set_parameter enableParallelHelperSpawn true
    set ::env(RT_TMP) "./.Xil/Vivado-936772-OSUTeststand2/realtime/tmp"
    if { [ info exists ::env(RT_TMP) ] } {
      file mkdir $::env(RT_TMP)
    }

    rt::delete_design

    rt::set_parameter datapathDensePacking false
    set rt::partid xc7k325tffg900-2
     file delete -force synth_hints.os

    set rt::multiChipSynthesisFlow false
    source $::env(SYNTH_COMMON)/common.tcl
    set rt::defaultWorkLibName xil_defaultlib
    rt::set_parameter defaultVhdlWorkLib xil_defaultlib

    rt::set_parameter loadVhdl2008Libs false
    rt::set_parameter loadVhdl2019Libs false
    rt::set_parameter deferParseUntilElab true
    rt::set_parameter sortHdlCommandLine true
    # Skipping read_* RTL commands because this is post-elab optimize flow
    set rt::useElabCache true
    if {$rt::useElabCache == false} {
      rt::read_verilog -sv -include {
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/vio_0/hdl/verilog
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/vio_0/hdl
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/tri_mode_ethernet_mac_0/hdl/avb
  } {
      /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_cdc/hdl/xpm_cdc.sv
      /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_memory/hdl/xpm_memory.sv
    }
      rt::read_verilog -include {
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/vio_0/hdl/verilog
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/vio_0/hdl
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz
    /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/tri_mode_ethernet_mac_0/hdl/avb
  } {
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/fifo32to8_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/fifo36x512_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/fifo8to32_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/fifo_128to128_depth1k_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/fifo_128to32_depth16k_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/gtwizard_0_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/tri_mode_ethernet_mac_0_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/vio_0_stub.v
      ./.Xil/Vivado-936772-OSUTeststand2/realtime/clockwiz_stub.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/CRC32_8gen.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/CRC32gen.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/DESER32b.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/DataX0Y3.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/Data_Aggregator.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/Data_Checker.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/Data_Source.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/Data_generator_160M.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/PRBS31Gen32b.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/PRBS31_Seed_Checker.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/PRBS7Gen32b.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/SER32b.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/SearchSamplePoint.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/Tx_PRBS7_Data_Checker.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/dataPrbs7Check.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/support/gtwizard_0_common.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/support/gtwizard_0_common_reset.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/gtwizard_0_exdes.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/support/gtwizard_0_gt_usrclk_source.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/gtwizard_0_ex/gtwizard_0_ex.srcs/sources_1/imports/example_design/support/gtwizard_0_support.v
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/new/GBCR2_SEU_Test.v
    }
      rt::read_vhdl -lib xpm /tools/Xilinx/Vivado/2024.1/data/ip/xpm/xpm_VCOMP.vhd
      rt::read_vhdl -lib xil_defaultlib {
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/arp.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/arp_cache2.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/bram_dp.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/com5402pkg.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/com5402.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/control_interface.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/gig_eth.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/gig_eth_mac_fifo_block.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/gig_eth_mac_resets.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/global_clock_reset.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/global_resetter.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/i2c/i2c_master.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/i2c/i2c_wr_bytes.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/packet_parsing.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/ping.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/tcp_rxbufndemux2.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/tcp_server.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/tcp_tx.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/tcp_txbuf.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/timer_4us.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/axi_lite_sm/tri_mode_ethernet_mac_0_axi_lite_sm.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/fifo/tri_mode_ethernet_mac_0_bram_tdp.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/common/tri_mode_ethernet_mac_0_reset_sync.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/fifo/tri_mode_ethernet_mac_0_rx_client_fifo.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/support/tri_mode_ethernet_mac_0_support.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/support/tri_mode_ethernet_mac_0_support_clocking.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/support/tri_mode_ethernet_mac_0_support_resets.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/common/tri_mode_ethernet_mac_0_sync_block.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/fifo/tri_mode_ethernet_mac_0_ten_100_1g_eth_fifo.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/KC705/fifo/tri_mode_ethernet_mac_0_tx_client_fifo.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/udp2serial.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/udp_rx.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/udp_tx.vhd
      /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/src/gig_eth/tcp_server/whois2.vhd
    }
      rt::filesetChecksum
    }
    rt::set_parameter usePostFindUniquification true
    set rt::SDCFileList ./.Xil/Vivado-936772-OSUTeststand2/realtime/GBCR2_SEU_Test_synth.xdc
    rt::sdcChecksum
    set rt::top GBCR2_SEU_Test
    rt::set_parameter enableIncremental true
    rt::set_parameter markDebugPreservationLevel "enable"
    set rt::reportTiming false
    rt::set_parameter elaborateOnly false
    rt::set_parameter elaborateRtl false
    rt::set_parameter eliminateRedundantBitOperator true
    rt::set_parameter dataflowBusHighlighting false
    rt::set_parameter generateDataflowBusNetlist false
    rt::set_parameter dataFlowViewInElab false
    rt::set_parameter busViewFixBrokenConnections false
    rt::set_parameter elaborateRtlOnlyFlow false
    rt::set_parameter writeBlackboxInterface true
    rt::set_parameter ramStyle auto
    rt::set_parameter merge_flipflops true
# MODE: 
    rt::set_parameter webTalkPath {/home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.cache/wt}
    rt::set_parameter synthDebugLog false
    rt::set_parameter printModuleName false
    rt::set_parameter enableSplitFlowPath "./.Xil/Vivado-936772-OSUTeststand2/"
    set ok_to_delete_rt_tmp true 
    if { [rt::get_parameter parallelDebug] } { 
       set ok_to_delete_rt_tmp false 
    } 
    if {$rt::useElabCache == false} {
        set oldMIITMVal [rt::get_parameter maxInputIncreaseToMerge]; rt::set_parameter maxInputIncreaseToMerge 1000
        set oldCDPCRL [rt::get_parameter createDfgPartConstrRecurLimit]; rt::set_parameter createDfgPartConstrRecurLimit 1
        $rt::db readXRFFile
      rt::run_synthesis -module $rt::top
        rt::set_parameter maxInputIncreaseToMerge $oldMIITMVal
        rt::set_parameter createDfgPartConstrRecurLimit $oldCDPCRL
    }

    set rt::flowresult [ source $::env(SYNTH_COMMON)/flow.tcl ]
    rt::HARTNDb_stopJobStats
    rt::HARTNDb_reportJobStats "Synthesis Optimization Runtime"
    rt::HARTNDb_stopSystemStats
    if { $rt::flowresult == 1 } { return -code error }


  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  rt::set_parameter helper_shm_key "" 
    if { [ info exists ::env(RT_TMP) ] } {
      if { [info exists ok_to_delete_rt_tmp] && $ok_to_delete_rt_tmp } { 
        file delete -force $::env(RT_TMP)
      }
    }

    source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  } ; #end uplevel
} rt::result]

if { $rt::rc } {
  $rt::db resetHdlParse
  set hsKey [rt::get_parameter helper_shm_key] 
  if { $hsKey != "" && [info exists ::env(BUILTIN_SYNTH)] && [rt::get_parameter enableParallelHelperSpawn] } { 
     $rt::db killSynthHelper $hsKey
  } 
  source $::env(HRT_TCL_PATH)/rtSynthCleanup.tcl
  return -code "error" $rt::result
}
