# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512.xci
# IP: The module: 'fifo36x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512.xci
# IP: The module: 'fifo36x512' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/fifo36x512/fifo36x512_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo36x512'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
