# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz.xci
# IP: The module: 'clockwiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz.xci
# IP: The module: 'clockwiz' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_late.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/ipcore_dir/clockwiz/clockwiz_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'clockwiz'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
