# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k.xci
# IP: The module: 'fifo_128to32_depth16k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.srcs/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k.xci
# IP: The module: 'fifo_128to32_depth16k' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k_clocks.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# XDC: /home/hep/Desktop/GBCR_Work/firmware/GBCR2_SEU_Test20220722/GBCR2_SEU_Test.gen/sources_1/ip/fifo_128to32_depth16k/fifo_128to32_depth16k_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'fifo_128to32_depth16k'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
